title: "OMERO Tools"
author: "BiAPoL"

execute:
  execute_notebooks: off

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
